name: Build and Push Container
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: Build Notebook Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Build with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository_owner }}/myproject
          ADDITIONAL_TAG: ${{ github.sha }}
